apiVersion: apps/v1
kind: Deployment 
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  replicas: 3
  selector:
    matchLables:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers: 
      - name: go-app-container
        image:  go/docker 
        ports:
        - containerPort: 9090
        env:
        - name: MYSQL_HOST
          valueFrom:
          configMapKeyRef:
            name: go-configmap
            key: host 
        - name: MYSQL_PORT
          valueFrom:
          configMapKeyRef:
            name: go-configmap
            key: port
        - name: MYSQL_USER
          valueFrom:
          secretKeyRef:
            name: go-configmap
            key: username
        - name: MYSQL_PASS  
          valueFrom:
          secretKeyRef:
            name: go-secret
            key: password