apiVersion: v1 
kind: Service 
metadata:
  name: go-app-service
spec:
  type: LoadBalancer
  selector:
    app: go-app
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  - name: https
    port: 443
    targetPort: 8443